title: dannydes
description: The thoughts of Daniel Desira.
url: http://localhost:4000
author: Daniel Desira
gems: ['jekyll-paginate', 'jekyll-feed']
paginate: 5
paginate_path: "/blog/page:num/"
tag_page_layout: tag_page
tag_page_dir: tags